### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ullbergm** [ullbergm/openshift#33]
# TODO List

## System
 - [x] Automated Certificates
 - [x] Synology iSCSI CSI driver
 - [x] Node Feature Discovery
 - [ ] Cert-Utils
 - [ ] Reflector ?
 - [ ] Reloader
 - [ ] MetalLB ?
 - [ ] Cloudflared
 - [ ] nginx-ingress
 - [ ] External-DNS
 - [ ] Authentic / Authelia ? (Use RH one?)
 - [ ] Gatus
 - [ ] ntfy
 - [ ] pod-gateway
 - [x] nmstate operator
 - [ ] k8tz
 - [ ] https://github.com/squat/generic-device-plugin
 - [ ] Smokeping
 - [ ] Goldpinger

## Apps
 - [x] Hajimari
 - [x] Plex
 - [x] sabnzbd
 - [x] bazarr
 - [x] gaps
 - [x] kavita
 - [x] lidarr
 - [x] overseerr
 - [x] prowlarr
 - [x] radarr
 - [x] readarr
 - [ ] [recyclarr](https://github.com/rust84/k8s-gitops/blob/main/k8s/clusters/cluster-0/manifests/media/recyclarr/recyclarr.yml)
 - [x] sonarr
 - [x] tautulli
 - [ ] tubearchivist
 - [x] cyberchef
 - [ ] paperless-ngx
 - [ ] monica
 - [ ] shlink
 - [x] [changedetection.io](https://github.com/dgtlmoon/changedetection.io)
 - [ ] [adguard-home](https://hub.docker.com/r/adguard/adguardhome)
 - [x] [chat-with-gpt](https://github.com/cogentapps/chat-with-gpt)
 - [x] whoogle
 - [ ] scrypted
 - [ ] actual (actualbudget/actual-server)
 - [ ] [tandoor] (https://github.com/TandoorRecipes/recipes)
 - [ ] [wallabag] (https://github.com/wallabag/wallabag)
 - [ ] [ragflow] (https://github.com/infiniflow/ragflow)
 - [ ] [exportarr] (https://github.com/onedr0p/exportarr)

## Concepts
- [ ] VPN
- [ ] Unified email notifications (with option to trap messages)
- [ ] Alerts
- [ ] VDI
- [x] OpenShift Virtualization
- [ ] Red Hat OpenShift Dev Spaces
- [ ] Red Hat OpenShift Serverless
- [ ] Red Hat OpenShift Service Mesh
- [ ] Web Terminal
- [ ] Security Scanning
